# SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:noway_5@47.101.140.135:3306/liar'
# local db
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:root@localhost:3306/liar'
SQLALCHEMY_COMMIT_ON_TEARDOWN = True

CSRF_ENABLED = True
SECRET_KEY = 'you-will-never-guess'

SQLALCHEMY_TRACK_MODIFICATIONS = False
JSON_AS_ASCII = False
SEARCH_NEWS_LIMITED = 20
SEARCH_SPEAKER_LIMITED = 20
SEARCH_PARTY_LIMITED = 20

SIM_LIMITED = 6
DEFAULT_MODEL_MODE = 5
